"""Golden tests for plugin registry to Compose fragments (T-FR-0003-05)."""

from __future__ import annotations

from pathlib import Path

import pytest

from hearth_install.layout import ensure_hearth_layout
from hearth_install.plugin_compose import (
    PluginRegistryError,
    generate_plugin_compose,
    write_default_plugin_registry,
)


def test_generate_plugin_compose_matches_golden_yaml(tmp_path: Path) -> None:
    hearth = ensure_hearth_layout(tmp_path, hearth_ref="compose-test")
    for slug in ("groceries", "recipes", "disabled"):
        (hearth / "plugins" / slug).mkdir(parents=True)

    registry = hearth / "state" / "plugins.yaml"
    registry.write_text(
        """\
schema: 1
plugins:
  - slug: groceries
    source_git: https://example.test/groceries.git
    enabled: true
    image: ghcr.io/example/groceries:0.1.0
    port: 8301
    env:
      GROCERIES_MODE: test
  - slug: recipes
    source_git: https://example.test/recipes.git
    enabled: true
    build: plugins/recipes
    command: ["python", "-m", "http.server", "8302"]
    port: 8302
  - slug: disabled
    source_git: https://example.test/disabled.git
    enabled: false
    image: ghcr.io/example/disabled:0.1.0
""",
        encoding="utf-8",
    )

    output = generate_plugin_compose(hearth)

    assert output == hearth / "compose" / "overrides" / "generated.plugins.yml"
    assert output.read_text(encoding="utf-8") == """\
# Generated by hearth_install.plugin_compose. Do not edit by hand.
services:
  groceries:
    image: ghcr.io/example/groceries:0.1.0
    restart: unless-stopped
    expose:
      - "8301"
    environment:
      GROCERIES_MODE: test
      HEARTH_HOME: /hearth
      HEARTH_PLUGIN_PORT: "8301"
      HEARTH_PLUGIN_SLUG: groceries
    volumes:
      - ../plugins/groceries:/app:ro
      - ../var/plugins/groceries:/var/hearth/plugins/groceries
  recipes:
    build:
      context: ../plugins/recipes
    command:
      - python
      - -m
      - http.server
      - "8302"
    restart: unless-stopped
    expose:
      - "8302"
    environment:
      HEARTH_HOME: /hearth
      HEARTH_PLUGIN_PORT: "8302"
      HEARTH_PLUGIN_SLUG: recipes
    volumes:
      - ../plugins/recipes:/app:ro
      - ../var/plugins/recipes:/var/hearth/plugins/recipes
"""


def test_write_default_plugin_registry_is_idempotent(tmp_path: Path) -> None:
    hearth = ensure_hearth_layout(tmp_path, hearth_ref="registry-test")
    registry = write_default_plugin_registry(hearth)
    first = registry.read_text(encoding="utf-8")

    registry.write_text(first + "# operator note\n", encoding="utf-8")
    assert write_default_plugin_registry(hearth).read_text(encoding="utf-8").endswith(
        "# operator note\n",
    )


def test_generate_plugin_compose_rejects_missing_plugin_dir(tmp_path: Path) -> None:
    hearth = ensure_hearth_layout(tmp_path, hearth_ref="missing-plugin-test")
    (hearth / "state" / "plugins.yaml").write_text(
        """\
schema: 1
plugins:
  - slug: missing
    source_git: https://example.test/missing.git
    enabled: true
    image: ghcr.io/example/missing:0.1.0
""",
        encoding="utf-8",
    )

    with pytest.raises(PluginRegistryError, match="hearth/plugins/missing"):
        generate_plugin_compose(hearth)
