"""Tests for repo-root ``./install`` bootstrap (T-FR-0003-03)."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest

from hearth_install import bootstrap
from hearth_install.layout import ensure_heart_layout
from hearth_install.plugin_compose import generate_plugin_compose


def test_dry_run_leaves_install_root_untouched(tmp_path: Path) -> None:
    target = tmp_path / "opt" / "hearth"
    assert not target.exists()

    code = bootstrap.run_bootstrap(
        ["--dry-run", "--repo-root", str(tmp_path), str(target)],
        env={},
    )

    assert code == 0
    assert not target.exists()


def test_dry_run_respects_hearth_install_root_env(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.delenv("HEARTH_INSTALL_ROOT", raising=False)
    root = tmp_path / "from-env"
    code = bootstrap.run_bootstrap(
        ["--dry-run", "--repo-root", str(tmp_path)],
        env={"HEARTH_INSTALL_ROOT": str(root)},
    )
    assert code == 0
    assert not root.exists()


def test_bootstrap_materializes_heart_and_shim(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """DEV path: layout, compose template, plugin stub, symlink — no compose up."""

    repo = tmp_path / "repo"
    (repo / "bin").mkdir(parents=True)
    (repo / "bin" / "hearth").write_text("#!/usr/bin/env false\n", encoding="utf-8")

    inst = tmp_path / "install"
    calls: list[tuple[list[str], str]] = []

    def fake_run(cmd: list[str], *, cwd: str, check: bool) -> subprocess.CompletedProcess[str]:  # noqa: ARG001
        calls.append((cmd, cwd))
        return subprocess.CompletedProcess(cmd, 0, "", "")

    code = bootstrap.run_bootstrap(
        [
            "--repo-root",
            str(repo),
            "--skip-docker-check",
            "--skip-compose-up",
            "--hearth-ref",
            "test-ref",
            str(inst),
        ],
        compose_runner=fake_run,
    )

    assert code == 0
    assert calls == []

    heart = inst / "heart"
    assert (heart / "VERSION.json").is_file()
    assert json.loads((heart / "VERSION.json").read_text(encoding="utf-8"))["hearth_ref"] == "test-ref"
    assert (heart / "compose" / "docker-compose.yml").is_file()
    assert (heart / "compose" / "overrides" / "generated.plugins.yml").is_file()
    shim = heart / "bin" / "hearth"
    assert shim.is_symlink()
    assert shim.resolve() == (repo / "bin" / "hearth").resolve()


def test_compose_up_invokes_docker(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    (repo / "bin").mkdir(parents=True)
    (repo / "bin" / "hearth").write_text("#!/usr/bin/env false\n", encoding="utf-8")
    inst = tmp_path / "install"

    checked = {"docker": False}

    def fake_verify(_stderr):  # noqa: ANN001
        checked["docker"] = True
        return True

    monkeypatch.setattr(bootstrap, "verify_docker_engine", fake_verify)

    calls: list[tuple[list[str], str]] = []

    def fake_run(cmd: list[str], *, cwd: str, check: bool) -> subprocess.CompletedProcess[str]:  # noqa: ARG001
        calls.append((cmd, cwd))
        return subprocess.CompletedProcess(cmd, 0, "", "")

    code = bootstrap.run_bootstrap(
        ["--repo-root", str(repo), "--skip-docker-check", str(inst)],
        compose_runner=fake_run,
    )

    assert code == 0
    assert not checked["docker"]
    heart = inst / "heart"
    expected_cmd = ["docker", "compose", "-f", "docker-compose.yml", "up", "-d"]
    assert calls == [(expected_cmd, str(heart / "compose"))]


def test_generate_plugin_compose_empty_registry_yaml(tmp_path: Path) -> None:
    """Regression: empty enabled set yields valid Compose YAML for ``include``."""

    heart = ensure_heart_layout(tmp_path, hearth_ref="empty-plugins")
    out = generate_plugin_compose(heart)
    assert out.read_text(encoding="utf-8") == (
        "# Generated by hearth_install.plugin_compose. Do not edit by hand.\n"
        "services: {}\n"
    )
